#cloud-config
autoinstall:
  version: 1

  source:
    id: ubuntu-server-minimal

 locale: en_US.UTF-8
  keyboard:
    layout: us
  timezone: Europe/Rome

  network:
    version: 2
    ethernets:
      enp1s0:
        dhcp4: true

  identity:
    username: usuario
    hostname: usuario
    password: 'usuario'

  packages:
    - git
    - python3-pip

  snaps:
    - name: pycharm-community
      channel: stable 
      classic: true

  shutdown: reboot